# For more info on HTTP files go to https://aka.ms/vs/httpfile
@address = http://localhost:5278/mcp


### 

POST {{address}}/tools/list                        
Content-Type: application/json
Accept: application/json,text/event-stream
{}