// <auto-generated />
using System;
using EntityFramework.DBProvider;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AterStudio.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    partial class CommandDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Entity.StudioMod.ApiDocInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalPath")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ApiDocInfos");
                });

            modelBuilder.Entity("Entity.StudioMod.ConfigData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ValueType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Configs");
                });

            modelBuilder.Entity("Entity.StudioMod.GenAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActionStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenApiPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Description");

                    b.HasIndex("Name");

                    b.HasIndex("ProjectId");

                    b.ToTable("GenActions");
                });

            modelBuilder.Entity("Entity.StudioMod.GenActionGenStep", b =>
                {
                    b.Property<Guid>("GenActionsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GenStepsId")
                        .HasColumnType("TEXT");

                    b.HasKey("GenActionsId", "GenStepsId");

                    b.HasIndex("GenStepsId");

                    b.ToTable("GenActionGenSteps");
                });

            modelBuilder.Entity("Entity.StudioMod.GenStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileType")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputContent")
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputPath")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplatePath")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("GenSteps");
                });

            modelBuilder.Entity("Entity.StudioMod.McpTool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptPath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("TemplatePaths")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("McpTools");
                });

            modelBuilder.Entity("Entity.StudioMod.ModelInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssemblyName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsEnum")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsList")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KeyType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Md5Hash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModuleName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NamespaceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ProjectId");

                    b.ToTable("ModelInfo");
                });

            modelBuilder.Entity("Entity.StudioMod.ModelProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AttributeText")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CommentSummary")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CommentXml")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("HasMany")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasSet")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsComplexType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDecimal")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnum")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsJsonIgnore")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsList")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNavigation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNullable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinLength")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ModelInfoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NavigationName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SuffixContent")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsEnum");

                    b.HasIndex("ModelInfoId");

                    b.HasIndex("Name");

                    b.HasIndex("Type");

                    b.ToTable("ModelProperties");
                });

            modelBuilder.Entity("Entity.StudioMod.Solution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SolutionType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Solutions");
                });

            modelBuilder.Entity("Entity.StudioMod.ApiDocInfo", b =>
                {
                    b.HasOne("Entity.StudioMod.Solution", "Project")
                        .WithMany("ApiDocInfos")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Entity.StudioMod.GenAction", b =>
                {
                    b.HasOne("Entity.StudioMod.Solution", "Project")
                        .WithMany("GenActions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Entity.StudioMod.Variable", "Variables", b1 =>
                        {
                            b1.Property<Guid>("GenActionId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("TEXT");

                            b1.HasKey("GenActionId", "__synthesizedOrdinal");

                            b1.ToTable("GenActions");

                            b1.ToJson("Variables");

                            b1.WithOwner()
                                .HasForeignKey("GenActionId");
                        });

                    b.Navigation("Project");

                    b.Navigation("Variables");
                });

            modelBuilder.Entity("Entity.StudioMod.GenActionGenStep", b =>
                {
                    b.HasOne("Entity.StudioMod.GenAction", "GenAction")
                        .WithMany()
                        .HasForeignKey("GenActionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.StudioMod.GenStep", "GenStep")
                        .WithMany()
                        .HasForeignKey("GenStepsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GenAction");

                    b.Navigation("GenStep");
                });

            modelBuilder.Entity("Entity.StudioMod.GenStep", b =>
                {
                    b.HasOne("Entity.StudioMod.Solution", "Project")
                        .WithMany("GenSteps")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Entity.StudioMod.McpTool", b =>
                {
                    b.HasOne("Entity.StudioMod.Solution", "Project")
                        .WithMany("McpTools")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Entity.StudioMod.ModelInfo", b =>
                {
                    b.HasOne("Entity.StudioMod.Solution", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Entity.StudioMod.ModelProperty", b =>
                {
                    b.HasOne("Entity.StudioMod.ModelInfo", "EntityInfo")
                        .WithMany("PropertyInfos")
                        .HasForeignKey("ModelInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntityInfo");
                });

            modelBuilder.Entity("Entity.StudioMod.Solution", b =>
                {
                    b.OwnsOne("Entity.StudioMod.SolutionConfig", "Config", b1 =>
                        {
                            b1.Property<Guid>("SolutionId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ApiPath")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("CommonModPath")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedTimeName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("EntityFrameworkPath")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("EntityPath")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("IdType")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsLight")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ModulePath")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("ServicePath")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("SharePath")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("SolutionPath")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("UpdatedTimeName")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Version")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("SolutionId");

                            b1.ToTable("Solutions");

                            b1.ToJson("Config");

                            b1.WithOwner()
                                .HasForeignKey("SolutionId");
                        });

                    b.Navigation("Config")
                        .IsRequired();
                });

            modelBuilder.Entity("Entity.StudioMod.ModelInfo", b =>
                {
                    b.Navigation("PropertyInfos");
                });

            modelBuilder.Entity("Entity.StudioMod.Solution", b =>
                {
                    b.Navigation("ApiDocInfos");

                    b.Navigation("GenActions");

                    b.Navigation("GenSteps");

                    b.Navigation("McpTools");
                });
#pragma warning restore 612, 618
        }
    }
}
