global using System;
global using System.ComponentModel.DataAnnotations;
global using Entity.CMSMod;
global using Ater.Common.Models;
global using Ater.Common.Utils;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Logging;
global using Share;
global using Share.Implement;
