global using System.ComponentModel.DataAnnotations;
global using System.Linq.Expressions;
global using System.Text;
global using System.Text.Json;
global using Entity.StudioMod;
global using EntityFramework;
global using EntityFramework.DBProvider;
global using Framework.Common.Models;
global using Framework.Common.Utils;
global using Framework.Web.Convention;
global using Microsoft.CodeAnalysis;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Logging;
global using Share.Helper;
global using Share.Models;
global using Project = Entity.StudioMod.Project;
global using PropertyInfo = CodeGenerator.Models.PropertyInfo;
