global using System.ComponentModel.DataAnnotations;
global using System.Linq.Expressions;
global using System.Text;
global using System.Text.Json;
global using Ater.Common.Models;
global using Ater.Common.Utils;
global using Ater.Web.Convention;
global using Entity.StudioMod;
global using EntityFramework;
global using EntityFramework.DBProvider;
global using Microsoft.CodeAnalysis;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Logging;
global using Share.Helper;
global using Share.Models;
global using PropertyInfo = CodeGenerator.Models.PropertyInfo;
global using Solution = Entity.StudioMod.Solution;
