// This file is generated by scripts/i18n-keys.js
// Do not edit this file directly.
/* eslint-disable */
export const I18N_KEYS = {
  "home": "home",
  "hello": "hello",
  "login": {
    "username": "login.username",
    "password": "login.password",
    "login": "login.login",
    "logout": "login.logout"
  },
  "language": "language",
  "validation": {
    "required": "validation.required",
    "minlength": "validation.minlength",
    "maxlength": "validation.maxlength"
  },
  "menu": {
    "business": "menu.business",
    "customer": "menu.customer",
    "team": "menu.team",
    "product": "menu.product",
    "order": "menu.order",
    "system": "menu.system",
    "systemRole": "menu.systemRole",
    "systemUser": "menu.systemUser",
    "systemLogs": "menu.systemLogs",
    "systemConfig": "menu.systemConfig"
  }
};
