// This file is generated by scripts/i18n-keys.js
// Do not edit this file directly.
/* eslint-disable */
export const I18N_KEYS = {
  "login": {
    "title": "login.title",
    "username": "login.username",
    "password": "login.password",
    "login": "login.login"
  },
  "language": "language"
};
