using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;

namespace Ater.Web.Analyzers.SourceGenerators;

[Generator(LanguageNames.CSharp)]
public class ResxConstGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var resxFiles = context.AdditionalTextsProvider.Where(file =>
            file.Path.EndsWith(".resx", StringComparison.OrdinalIgnoreCase)
        );

        var compilationAndResx = context.CompilationProvider.Combine(resxFiles.Collect());

        context.RegisterSourceOutput(
            compilationAndResx,
            (spc, pair) =>
            {
                var (compilation, resxList) = (pair.Left, pair.Right);
                var allKeys = new HashSet<string>();

                foreach (var file in resxList)
                {
                    var text = file.GetText()?.ToString();
                    if (string.IsNullOrWhiteSpace(text))
                    {
                        continue;
                    }

                    // 解析 .resx，提取 keys
                    var doc = XDocument.Parse(text);
                    var keys = doc.Descendants("data")
                        .Select(e => e.Attribute("name")?.Value)
                        .Where(n => !string.IsNullOrWhiteSpace(n))
                        .Distinct();
                    foreach (var key in keys)
                    {
                        allKeys.Add(key!);
                    }
                }

                if (allKeys.Count == 0)
                {
                    return;
                }

                // 查找 Localizer 类
                var localizerClass = compilation
                    .SyntaxTrees.SelectMany(tree =>
                        tree.GetRoot()
                            .DescendantNodes()
                            .OfType<Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax>()
                    )
                    .FirstOrDefault(cls => cls.Identifier.Text == "Localizer");

                string ns = GetNamespace(localizerClass);
                if (localizerClass != null)
                {
                    var nsNode = localizerClass.Parent;
                    while (
                        nsNode != null
                        && nsNode
                            is not Microsoft.CodeAnalysis.CSharp.Syntax.NamespaceDeclarationSyntax
                        && nsNode
                            is not Microsoft
                                .CodeAnalysis
                                .CSharp
                                .Syntax
                                .FileScopedNamespaceDeclarationSyntax
                    )
                    {
                        nsNode = nsNode.Parent;
                    }
                    if (
                        nsNode
                        is Microsoft.CodeAnalysis.CSharp.Syntax.BaseNamespaceDeclarationSyntax nsDecl
                    )
                    {
                        ns = nsDecl.Name.ToString();
                    }
                }

                // 生成 partial class
                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated/>");
                sb.AppendLine($"namespace {ns};");
                sb.AppendLine("public partial class Localizer");
                sb.AppendLine("{");
                foreach (var key in allKeys.OrderBy(k => k))
                {
                    string valName = key;
                    if (int.TryParse(valName, out _))
                    {
                        valName = $"_{valName}";
                    }
                    if (valName.Contains('-'))
                    {
                        valName = valName.Replace('-', '_');
                    }
                    sb.AppendLine($"    public const string {valName} = \"{key}\";");
                }
                sb.AppendLine("}");

                spc.AddSource("Localizer.g.cs", sb.ToString());
            }
        );
    }

    // 简单实现：从cs文件读取namespace（假设namespace在前几行）
    private static string GetNamespace(
        Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax classDecl
    )
    {
        var ns = classDecl.Parent;
        while (
            ns != null
            && ns is not Microsoft.CodeAnalysis.CSharp.Syntax.NamespaceDeclarationSyntax
            && ns is not Microsoft.CodeAnalysis.CSharp.Syntax.FileScopedNamespaceDeclarationSyntax
        )
        {
            ns = ns.Parent;
        }
        if (ns is Microsoft.CodeAnalysis.CSharp.Syntax.BaseNamespaceDeclarationSyntax nsDecl)
        {
            return nsDecl.Name.ToString();
        }
        return "Share.Localizer";
    }
}
